### ISSUE TITLE
Clear up documentation on IOS installation

### ISSUE THREAD

**Issue by the-simian** [taggon/react-native-intl#2]
"To translate messages, create i18n folder and put .mo files into it. Drag the folder to just below the project in Xcode. Choose Create folder references."

I'm not entirely sure what this is trying to suggest. 
Where do you create the folder, exactly? 
Where are the .mo files?

Maybe some more detail might help myself, and others.

**Comment by taggon** [comment]
> Where do you create the folder, exactly? 

In fact, it doesn't matter. But the updated documentation says that you can create the `i18n` folder in your React Native project's root. You can see where the `i18n` folder is in the example project.

> Where are the `.mo` files?

The `i18n` folder you created for your own project. You can see two `.mo` files in the `i18n` folder of the example project.

Any other questions?

**Comment by the-simian** [comment]
When you say example project, I"m looking here: https://github.com/facebook/react-native/tree/master/Examples but I don't see what your'e describing, maybe you could link the example you mean?

**Comment by taggon** [comment]
Because it is not an official project of React Native, you should look for the example in this repository.
https://github.com/taggon/react-native-intl/tree/master/Examples/Hello

**Comment by taggon** [comment]
I thought now you are able to know where you should put the .mo files into. Let me know if you need more.
