### ISSUE TITLE
Update to work with React Native 0.40

### ISSUE THREAD

**Issue by wachunei** [taggon/react-native-intl#4]
According to [0.40 release changelog](https://github.com/facebook/react-native/releases/tag/v0.40.0) a breaking change is introduced for iOS modules, needing a major version bump to work with this release.

**Comment by wachunei** [comment]
Pull Requested #5
I've tested it in a new project using `npm install` from my branch, it worked!

**Comment by taggon** [comment]
Closed by merging https://github.com/taggon/react-native-intl/pull/5
